version: '3'

services:

 redmine:
   # Image source: https://hub.docker.com/_/redmine/
   container_name: redmine
   build:
     context: .
     dockerfile: Dockerfile
   ports:
    - "3000:3000"
   environment:
     REDMINE_DB_MYSQL: db
     REDMINE_DB_USERNAME: redmineu
     REDMINE_DB_PASSWORD: redminep
     REDMINE_DB_DATABASE: redmined
   volumes:
    - "redmine_data:/usr/share/redmine"

 db:
   container_name: db
   # Image source: https://hub.docker.com/_/mariadb/
   image: "mariadb:10.4"
   restart: always
   ports:
     - 3306
   environment:
     MYSQL_ROOT_PASSWORD: rootp
     MYSQL_USER: redmineu
     MYSQL_PASSWORD: redminep
     MYSQL_DATABASE: redmined
   volumes:
    - "mysql_data:/var/lib/mysql"

volumes:
  redmine_data:
    driver: local

  mysql_data:
    driver: local
